# Site settings
title: Ogma
email: 
description: > # this means to ignore newlines until "baseurl:"
  The Ogma Project Devblog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ogma-project.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
